version: "2.0"

services:

  # Solr instance for running tests against
  solr:
    image: ukwa/webarchive-discovery-solr

  # Solr Proxy
  solr-proxy:
    build: .
    environment:
     - "SOLR_URL=http://solr:8983/solr/discovery"
    ports:
     - 8983:80
